version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint
      - apt-get update && apt-get install -y libjpeg-dev zlib1g-dev
      - pip install --upgrade pip
  pre_build:
    commands:
      - pylint $CODEBUILD_SRC_DIR/bookshelf_project/* || true
artifacts:
  files:
    - '/*'